version: "3.9"

services:
  api:
    image: natley30/api
    container_name: api
    ports:
    - "5000:5000"
    restart: always

  web:
    image: natley30/web
    container_name: web
    ports:
    - "8501:8501"
    environment:
    - API_URL=http://api:5000/predict
    depends_on:
    - api
    restart: always